Fix missing args in `tfe.stats.RunningVariance.from_shape`
Both the `event_ndims` and `name` arguments of the class method
`tfp.experimental.stats.RunningVariance.from_shape` were missing,
causing `TypeError: from_example() got an unexpected keyword argument
'event_ndims'`.