Bug fixes to tfd.Wishart.
1. Fixes a sampling and log_prob bug in 0-sized Wishart distributions.
Before this change, the added tests failed with the error:
Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
and
Cannot reshape a tensor with 1 elements to shape [0,1,?] (0 elements) for 'Wishart_1/log_prob/Reshape_1' (op: 'Reshape') with input shapes: [1,1,1], [3] and with input tensors computed as partial shapes: input[1] = [0,1,?].

2. Fixes a log_prob bug when x is meant to be broadcast over the batch of parameters.
Before this change, the added test failed with the error:
ValueError: Requires start <= limit when delta > 0: 0/-2 for 'Wishart/log_prob/range_1' (op: 'Range') with input shapes: [], [], [] and with computed input tensors: input[0] = <0>, input[1] = <-2>, input[2] = <1>.
PiperOrigin-RevId: 239389971