Add assertAllAssertsNested, which makes nice errors when doing asserts on nested objects.
E.g.

```
self.assertAllAssertsNested(
     self.assertEqual, {
         'a': 3,
         'b': 4
     }, {
         'a': 3,
         'b': 5
     }, msg='assert failed')

=>

assert failed:

Structure 0:
{'a': 3, 'b': 4}

Structure 1:
{'a': 3, 'b': 5}

Exceptions:

Path: b
Exception: AssertionError
4 != 5
```

Switch assertAllEqualNested to use it.

PiperOrigin-RevId: 298971574