Disabled __iter__ on tfp.Distribution
After a recent change tfp.Distribution became implicitly iterable via
__getitem__. This led to confusing error messages when a distribution
was used as an iterable, e.g.

  a, b = distribution

results in

  ValueError: slice index 2 of dimension 0 out of bounds. for [...]

instead of

  TypeError: 'Distribution' is not iterable.

PiperOrigin-RevId: 237816241